GitHub Actions: Improve versioning

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -18,50 +18,49 @@ jobs:
     steps:
     - uses: actions/checkout@v4
     - name: Restore cached ~/.stack
-      id: cache-restore
       uses: actions/cache/restore@v4
       with:
-        path: |
-          ~/.local/bin/stack
-          ~/.stack
-        key: test-${{ runner.os }}-${{ hashFiles('stack.lts.yaml') }}
+        path: ~/.local/bin/stack-2.15.7
+        key: stack-2.15.7
     - run: |
-        if [ ! -f ~/.local/bin/stack ]; then
-          curl -sSL https://get.haskellstack.org/ | sh -s - -d ~/.local/bin
+        if [ ! -f ~/.local/bin/stack-2.15.7 ]; then
+          curl -o ~/.local/bin/stack-2.15.7 -L https://github.com/commercialhaskell/stack/releases/download/v2.15.7/stack-2.15.7-linux-x86_64-bin
         fi
     - name: Save ~/.stack
       uses: actions/cache/save@v4
       with:
-        path: |
-          ~/.local/bin/stack
-          ~/.stack
-        key: test-${{ runner.os }}-${{ hashFiles('stack.lts.yaml') }}
+        path: ~/.local/bin/stack-2.15.7
+        key: stack-2.15.7
 
   stack-test:
     runs-on: ubuntu-latest
     needs: install-stack
     steps:
     - uses: actions/checkout@v4
-    - name: Restore cached ~/.stack
-      id: cache-restore
+    - name: Restore cached Stack
+      id: restore-stack-binary
       uses: actions/cache/restore@v4
       with:
-        path: |
-          ~/.local/bin/stack
-          ~/.stack
-        key: test-${{ runner.os }}-${{ hashFiles('stack.lts.yaml') }}
-    - if: steps.cache-restore.outputs.cache-hit != 'true'
-      run: exit 1
+        path: ~/.local/bin/stack-2.15.7
+        key: stack-2.15.7
+    - if: steps.restore-stack-binary.outputs.cache-hit != 'true'
+      run: |
+        echo "stack-2.15.7 cannot be found (This should not happen; There's something wrong with the workflow file)"
+        exit 1
+    - name: Restore cached ~/.stack
+      id: restore-stack-directory
+      uses: actions/cache/restore@v4
+      with:
+        path: ~/.stack
+        key: stack-dir-lts-22.28
     - run: |
-        ~/.local/bin/stack init
-        ~/.local/bin/stack test
+        ~/.local/bin/stack-2.15.7 init --resolver=lts-22.28
+        ~/.local/bin/stack-2.15.7 test --resolver=lts-22.28
     - name: Save ~/.stack
       uses: actions/cache/save@v4
       with:
-        path: |
-          ~/.local/bin/stack
-          ~/.stack
-        key: test-${{ runner.os }}-${{ hashFiles('stack.lts.yaml') }}
+        path: ~/.stack
+        key: stack-dir-lts-22.28
 
   fourmolu:
     runs-on: ubuntu-latest
